# Generated by Django 3.2.9 on 2022-04-04 21:01

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('external_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя в соц сети')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Пользователи profile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=255)),
                ('eng', models.CharField(max_length=255)),
                ('context', models.CharField(default='', max_length=3000)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 5, 0, 1, 36, 40249))),
                ('reply_date', models.DateTimeField(default='2022-04-05 00:01:36')),
                ('user', models.ManyToManyField(to='web.CastomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Время получения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.castomuser', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
