# Generated by Django 3.2.9 on 2022-04-30 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_castomuser_message_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 18, 34, 53, 406220)),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.DateTimeField(default=1651332893.40622),
        ),
    ]
