# Generated by Django 3.2.9 on 2022-04-30 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220430_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 23, 32, 28, 895938)),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.DateTimeField(default=1651350748.895938),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ManyToManyField(related_name='user', to='web.CastomUser'),
        ),
    ]
