# Generated by Django 3.2.9 on 2022-05-01 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220501_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='number_responses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество проверок слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='context',
            field=models.CharField(default='', max_length=3000, verbose_name='Контекст слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 18, 5, 21, 184358), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='eng',
            field=models.CharField(max_length=255, verbose_name='Английское слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='is_remember',
            field=models.BooleanField(default=False, verbose_name='Выучил ли человек слово или нет'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1651417521.184358, verbose_name='Дата и время проверки слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='ru',
            field=models.CharField(max_length=255, verbose_name='Русское слово'),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ManyToManyField(related_name='user', to='web.CastomUser', verbose_name='Пользователь'),
        ),
    ]
