# Generated by Django 3.2.9 on 2022-05-10 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220501_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 21, 43, 12, 576610), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1652208192.57661, verbose_name='Дата и время проверки слова'),
        ),
    ]
