# Generated by Django 3.2.9 on 2022-05-10 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20220510_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='voice',
        ),
        migrations.AddField(
            model_name='word',
            name='bot_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пусть до файла для бота'),
        ),
        migrations.AddField(
            model_name='word',
            name='front_path',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Путь до файла для фронта'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 22, 48, 17, 607306), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1652212097.607306, verbose_name='Дата и время проверки слова'),
        ),
    ]
