# Generated by Django 3.2.9 on 2022-05-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220511_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='kukeev1999@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 19, 20, 40, 988022), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1652718040.988022, verbose_name='Дата и время проверки слова'),
        ),
    ]
