# Generated by Django 3.2.9 on 2022-05-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20220518_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 48, 56, 3613), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1652899736.003613, verbose_name='Дата и время проверки слова'),
        ),
    ]
