# Generated by Django 3.2.9 on 2022-05-31 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20220531_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodels',
            name='created',
            field=models.DateTimeField(auto_now=True, max_length='255', verbose_name='Время лога'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 23, 53, 24, 457676), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1654030404.457676, verbose_name='Дата и время проверки слова'),
        ),
    ]
