# Generated by Django 3.2.9 on 2022-05-31 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20220531_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodels',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время лога'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 0, 13, 13, 155614), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1654031593.155614, verbose_name='Дата и время проверки слова'),
        ),
    ]
