# Generated by Django 3.2.9 on 2022-05-31 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20220601_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodels',
            name='created',
            field=models.DateTimeField(verbose_name='Время лога'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 2, 6, 13, 495266), verbose_name='Дата добавления слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='reply_date',
            field=models.IntegerField(default=1654038373.495266, verbose_name='Дата и время проверки слова'),
        ),
    ]
